name: flutter_appwrite_quizeee
description: Trivia Application with Appwrite
publish_to: 'none'
version: 1.0.0+1

# Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^6.0.0
  url_launcher: ^6.1.0
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_appwrite: null
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/